"""chenge RoomsFacilitiesOrm

Revision ID: c059f5ecc554
Revises: 05ad50b69728
Create Date: 2024-10-25 23:05:42.319508

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c059f5ecc554"
down_revision: Union[str, None] = "05ad50b69728"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
